### PR TITLE
Add opportunity to disable parse mode

### PR DESCRIPTION
**Pull request by arsenron**

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
Afaic telegram bot API doesn't support "None" parse mode. Moreover, you can already "disable" parse mode by just setting the corresponding field of a request to `None` (or not enabling it in the first place).

**Comment by arsenron** [comment]
Yeah, I also was not able to find None parse mode in the docs either, but the API itself turns off parsing mode with this value. But it may be it is unstable, though. You mean I should do something ike this:
```
use teloxide_core::requests::HasPayload;

let mut req = bot.something().payload_mut();
req.parse_mode = None;
 ```
? So it is no problem if I need to do it once, but if there are multiple times in one function, it seems to be redundant. So, maybe it would make sense to create method like "disable_parse_mode()" or if ParseMode matches None, skip the field? It will be helpful in case of multiple messages of different formattings sent by a bot.

**Comment by Hirrolot** [comment]
By default, `.parse_mode` is set to `None`. If it isn't `None`, then you use the `DefaultParseMode` adaptor. Then you can try calling [`DefaultParseMode::inner`](https://docs.rs/teloxide/latest/teloxide/adaptors/struct.DefaultParseMode.html#method.inner) to get the underlying bot from the adaptor and call methods on it as they'll be without `.parse_mode`. @WaffleLapkin, please correct me if I'm wrong somewhere.

**Comment by arsenron** [comment]
Yeah, it works, but if I have two adaptors (DefaultParseMode and AutoSend), to turn off parse mode, I have to call inner 2 times like: 
```
bot.inner().inner().something()
```
So, it is no problem, but I wish I could do it i a more elegant way :)

**Comment by Hirrolot** [comment]
Well, you can write `DefaultParseMode::inner(AutoSend::inner(bot))` to clearly show your intention.

**Comment by WaffleLapkin** [comment]
@arsenron you can make an extension to turn off parse_mode:
```rust
trait DisableParseMode {
    fn disable_parse_mode(self) -> Self;
}

impl<R> DisableParseMode for R 
where
    R: HasPayload,
    R::Payload: HasParseMode,
{
    fn disable_parse_mode(mut self) -> Self {
        *self.parse_mode_field() = None;
        self
    }

trait HasParseMode {
    fn parse_mode_field(&mut self) -> &mut Option<ParseMode>;
}

impl HasParseMode for SendMessage { ... }
// etc
```

But generally, I think that you shouldn't use `DefaultParseMode` if there are a lot of places where you need to disable parse_mode.

**Comment by arsenron** [comment]
Ok, I will think about my implementation, sorry guys for wasting your time ;)

**Pull request closed without merging**
