### PR TITLE
Fixed message's URLs for private chats and a typo

### PR DESCRIPTION
**Pull request by hex0x0000**
Message's URLs don't use the whole chat id, they remove the prefix (-100)

### CODE REVIEW

**Comment by WaffleLapkin** [comment]
@hex0x0000 everything is looking good. Can you rebase-on-master and squash the commits though?

**Comment by hex0x0000** [comment]
@WaffleLapkin done. Should i make a new pull request? Because i can't change the pr's head from `url_fix` to `master`

**Comment by WaffleLapkin** [comment]
@hex0x0000 I don't quite understand wdym... If you are on the `url_fix` branch with commits squashed, can't you just `git push fork url_fix --force-with-lease`?

**Comment by hex0x0000** [comment]
[I did what you said](https://github.com/hex0x0000/teloxide-core/commit/2c53236af4691e334386b4d4e29de8f6d0aae5d8), idk maybe i misunderstood something?

**Comment by WaffleLapkin** [comment]
I see you moved everything to `master`. I thought you'd stay within the `url_fix` branch, just rebase it on master (as in `git rebase master`). Either way, it doesn't really matter, you can open a PR from your `master` branch, since you did it this way.

**Comment by hex0x0000** [comment]
@WaffleLapkin moving to #114

**Pull request closed without merging**
