### PR TITLE
Tune markups

### PR DESCRIPTION
**Pull request by Hirrolot**

### CODE REVIEW

**Comment by Hirrolot** [comment]
@WaffleLapkin, what do you think about an alternative to `InlineKeyboardButton::callback` that accepts a single argument? I mean `callback(x)` is equal to `callback(x, x)`. Because it seems that most of the time we just use the same argument for both of the function parameters.

**Comment by Hirrolot** [comment]
Maybe accept `Into<Option<String>>` as a second parameter? As in `.for_each_concurrent` in Tokio.

**Comment by Hirrolot** [comment]
Or maybe we just create a macro for callback data? Like `callback_data! { {"A", "B", "C"}, {"D", "E", "F"} }` or something like that.

**Comment by WaffleLapkin** [comment]
> what do you think about an alternative to InlineKeyboardButton::callback that accepts a single argument?

@Hirrolot I don't really like this idea. It works well in examples, but probably works poorly in "real life" -- with localization or some parameters that are passed via the data.

**Comment by Hirrolot** [comment]
Do you have an idea on how to simplify the reply keyboard construction in `examples/purchase.rs`?

**Comment by WaffleLapkin** [comment]
I was thinking of implementing `From<[[(A, B); N]; M]> where N: usize, M: usize, A: Into<String>, B: Into<String>`. Or maybe the same thing but with `IntoIterator`, instead of arrays. Also maybe implementing `FromIterator` maybe nice, so you could `.collect()` into a keyboard.

**Comment by Hirrolot** [comment]
Maybe this is not a perfect solution because besides `callback`, there are also methods like `switch_inline_query` that accept two strings. So it may not be clear what this transformation does.

**Comment by WaffleLapkin** [comment]
Another idea may be to create shortcuts, so you don't need to write types everywhere

**Review by WaffleLapkin — APPROVED** [review]

**Pull request merged**
