### PR TITLE
Rename `StickerType`

### PR DESCRIPTION
**Pull request by WaffleLapkin**
- Rename `StickerType` => `InputSticker`
- Rename `{CreateNewStickerSet,AddStickerToSet}::sticker_type}` => `sticker`

This just makes more sense.

### CODE REVIEW

**Comment by Hirrolot** [comment]
Actually I see no reason to change the current naming. `InputSticker` is not more intuitive as for me, the same holds for `sticker_type` -> `sticker`.

**Comment by WaffleLapkin** [comment]
@Hirrolot InputSticker is consistent with InputFile (and InputMedia) and highlights the fact that it's a type which we are sending to telegram (and not vise versa).

In my opinion, -Type fits bad here, because it's not actually a type, it's just a sticker.

**Comment by Hirrolot** [comment]
@WaffleLapkin Okay, now I'm convinced with the Input prefix. But what about sticker_type -> sticker? We already have Sticker (not to be confused with InputSticker). Maybe sticker_type -> input_sticker?

**Comment by WaffleLapkin** [comment]
@Hirrolot I've choose just sticker b/c
1) It's closer to original {png,tgs}_stiker
2) We don't often call args/fields after types (e.g.: kind and not message_kind, target and not target_message, etc)

**Review by Hirrolot — APPROVED** [review]

**Pull request merged**
